name: Test eBPF Probe

on:
  workflow_dispatch:

jobs:
  ebpf-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bpfcc-tools linux-headers-$(uname -r) python3-bpfcc

      - name: Mount debugfs
        run: |
          sudo mount -t debugfs none /sys/kernel/debug || true

      - name: Run eBPF execve test
        run: |
          cat > exec_probe.py <<'EOF'
          from bcc import BPF

          bpf_code = """
          #include <uapi/linux/ptrace.h>
          TRACEPOINT_PROBE(syscalls, sys_enter_execve) {
              char comm[16];
              bpf_get_current_comm(&comm, sizeof(comm));
              bpf_trace_printk("[EXECVE] %s\\n", comm);
              return 0;
          }
          """
          b = BPF(text=bpf_code)
          print("🚀 Tracing execve...")
          while True:
              (task, pid, cpu, flags, ts, msg) = b.trace_fields()
              print(f"{ts}: {msg}")
          EOF

          # Run for 10s, trigger some execs
          (sudo timeout 10s python3 exec_probe.py &) 
          sleep 2
          ls /bin >/dev/null
          echo "done"
